### ISSUE TITLE
Change number_of_iterations to default_number_of_iterations

### ISSUE THREAD

**Issue by andrrizzi** [MobleyLab/yank-restraints#2]
I went through most of the YAML scripts, and they should be mostly compatible with the latest YANK.

I think the only change required is to convert
```yaml
options:
  number_of_iterations: 500
```
to
```yaml
options:
  default_number_of_iterations: 500
```
The reason for this change is that it is now possible to specify the number of iterations separately for each sampler (see http://getyank.org/latest/yamlpages/samplers.html). When specified, the per-sampler `number_of_iterations` has priority over the general `options.default_number_of_iterations`.

Also, notice that with the latest YANK release you can specify multiple experiments in a single YAML file this way

```yaml
# Define an anchor to avoid redefining multiple times the same thing.
# This is completely optional, but it saves a few lines.
common_experiment: &common_experiment
  system: explicit
  protocol: absolute-binding

experiment-harmonic:  # this can be any name you want
  <<: *common_experiment
  restraint:
    type: Harmonic

experiment-boresch:
  <<: *common_experiment
  restraint:
    type: Boresch
    restrained_receptor_atoms: MDTraj DSL string
    restrained_ligand_atoms: MDTraj DSL string

experiment-flatbottom05:
  <<: *common_experiment
  restraint:
    type: FlatBottom
    well_radius: 0.5 * nanometers
    # For the experiment that tries multiple flatbottom restraints you can use !Combinatorial
    # well_radius: !Combinatorial [0.5 * nanometers, 1.5*nanometers, 2*nanometers, 3.5*nanometers]

...

experiment-null:
  <<: *common_experiment

experiments: [experiment-harmonic, experiment-boresch, experiment-flatbottom05, ..., experiment-null]
```
It'll work correctly the way it is currently structured too, but you may prefer a more compact description of your experiments if the rest of your input files is identical so that you won't have to change 6 YAML files every time you tweak the options.
